### PR TITLE
Allow to read kdegobals configuration

### PR DESCRIPTION
**Pull request by grulja**

### CODE REVIEW

**Comment by gottcode** [comment]
I'm curious, what issue is this solving? Wouldn't every Qt or KDE program need this, too? Unless there is some specific reason Tanglet needs access to the user's global settings, which I can't think of...

I'm not opposed to merging this, I just want to understand why first. And see if I need to add this to all of my other Flatpaks, as they are also pure Qt programs as well.

**Comment by grulja** [comment]
This is needed for every Qt/KDE applications, if you want to follow KDE Plasma color theme, icons, fonts etc. in case your application is running in Plasma session. If this is not allowed, your application will use default configuration, e.g. using default Breeze theme even when user is running a dark variant.

I didn't open review for every Qt application in flathub, because there is tons of them, that's why I sent an email on flatpak-devel mailing list about this.

**Comment by gottcode** [comment]
I'm not subscribed to the flatpak devel list, which is how I missed the heads up about this. I just saw the related KDE bugreport about the global menu; do I need to add --talk-name=com.canonical.AppMenu.Registrar to all of my flatpaks as well?

**Comment by grulja** [comment]
Yes, if you want your app to support global menu.

**Pull request merged**
